# Generated by Django 5.0.3 on 2024-03-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_topics_room_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topics',
            new_name='Topic',
        ),
    ]
