# Generated by Django 5.0.3 on 2024-03-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='room',
        ),
    ]
