# Generated by Django 5.0.3 on 2024-03-18 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_rename_name_room_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room',
        ),
    ]
