# Generated by Django 5.0.3 on 2024-03-20 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_remove_message_room_message_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room',
            new_name='name',
        ),
        migrations.AddField(
            model_name='room',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 16, 1, 28, 25, 422677, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
