# Generated by Django 5.0.3 on 2024-03-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0011_rename_room_room_name_room_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='messages',
        ),
    ]
