# Generated by Django 5.0.3 on 2024-03-21 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0014_message_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 16, 1, 28, 25, 422677, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
